# Generated by Django 4.1.3 on 2022-12-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003')], max_length=50, verbose_name='Аудитория')),
                ('time', models.CharField(choices=[('9', '09:00'), ('11', '11:00'), ('13', '13:00')], max_length=50, verbose_name='Время начала')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
