# Generated by Django 4.1.3 on 2022-12-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата занятия'),
        ),
    ]
