# Generated by Django 4.1.3 on 2022-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
    ]
